import base64
import json
import os
import uuid

import cv2
import numpy as np
from flask import Blueprint, current_app, jsonify, request

from database.db import get_db
from middleware import token_required
from models.detector import detect_face
from models.recognizer import get_embedding, l2_normalize

voters_bp = Blueprint('voters', __name__)

def _decode_base64_image(base64_string):
    if ',' in base64_string:
        base64_string = base64_string.split(',')[1]
    img_bytes = base64.b64decode(base64_string)
    np_arr = np.frombuffer(img_bytes, np.uint8)
    return cv2.imdecode(np_arr, cv2.IMREAD_COLOR)


def _generate_voter_id():
    # Short, URL-safe-ish identifier. Still enforced unique by DB.
    return f"V{uuid.uuid4().hex[:10].upper()}"


@voters_bp.route('/register', methods=['POST'])
@token_required
def register_voter():
    # Supervisor update: registration is keyed by citizenship number (unique),
    # voter_id is generated by the system, and faces come from webcam captures.
    if not request.is_json:
        return jsonify({
            'message': 'Registration must be JSON with citizenship_no and 10 webcam images.'
        }), 400

    data = request.get_json(silent=True) or {}
    name = (data.get('name') or '').strip()
    citizenship_no = (data.get('citizenship_no') or '').strip()
    phone = (data.get('phone') or '').strip()
    address = (data.get('address') or '').strip()
    images = data.get('images') or []

    if not name or not citizenship_no:
        return jsonify({'message': 'Name and citizenship number are required'}), 400

    if not isinstance(images, list) or len(images) < 10:
        return jsonify({'message': 'Please capture and submit 10 webcam photos'}), 400

    db = get_db()

    existing = db.execute(
        'SELECT id FROM voters WHERE citizenship_no = ?',
        (citizenship_no,)
    ).fetchone()
    if existing:
        return jsonify({'message': 'Citizenship number already registered'}), 409

    voter_id = _generate_voter_id()

    embeddings = []
    representative_frame = None

    for img_b64 in images[:10]:
        frame = _decode_base64_image(img_b64) if isinstance(img_b64, str) else None
        if frame is None:
            continue
        if representative_frame is None:
            representative_frame = frame

        result = detect_face(frame)
        if result is None:
            continue

        pil_face = result[0]
        emb = l2_normalize(get_embedding(pil_face))
        embeddings.append(emb.tolist())

    if len(embeddings) < 7:
        return jsonify({
            'message': 'Could not detect a clear face in enough frames. Please recapture in good lighting.'
        }), 400

    photo_filename = None
    if representative_frame is not None:
        photo_filename = f"{voter_id}_capture1.jpg"
        photo_path = os.path.join(current_app.config['VOTER_PHOTOS_FOLDER'], photo_filename)
        cv2.imwrite(photo_path, representative_frame)

    db.execute(
        '''
        INSERT INTO voters (name, voter_id, citizenship_no, phone, address, photo_path)
        VALUES (?, ?, ?, ?, ?, ?)
        ''',
        (name, voter_id, citizenship_no, phone, address, photo_filename or '')
    )
    db.commit()

    new_voter = db.execute('SELECT id FROM voters WHERE voter_id = ?', (voter_id,)).fetchone()

    voter_db_id = new_voter['id']
    for emb in embeddings[:10]:
        db.execute(
            'INSERT INTO voter_embeddings (voter_db_id, embedding_json) VALUES (?, ?)',
            (voter_db_id, json.dumps(emb))
        )
    db.commit()

    return jsonify({
        'message': 'Voter registered successfully',
        'voter_id': voter_id,
        'id': new_voter['id']
    }), 201


@voters_bp.route('', methods=['GET'])
@token_required
def get_voters():
    db = get_db()
    rows = db.execute(
        '''
        SELECT id, name, voter_id, citizenship_no, phone, address, photo_path,
               has_voted, registered_at
        FROM voters ORDER BY registered_at DESC
        '''
    ).fetchall()

    voters = [{
        'id': row['id'],
        'name': row['name'],
        'voter_id': row['voter_id'],
        'citizenship_no': row['citizenship_no'] or '',
        'phone': row['phone'] or '',
        'address': row['address'] or '',
        'photo_url': row['photo_path'],
        'status': 'voted' if row['has_voted'] else 'not-voted',
        'registered_at': row['registered_at']
    } for row in rows]

    return jsonify(voters), 200


@voters_bp.route('/<int:voter_db_id>', methods=['DELETE'])
@token_required
def delete_voter(voter_db_id):
    db = get_db()
    voter = db.execute(
        'SELECT id, voter_id, photo_path FROM voters WHERE id = ?',
        (voter_db_id,)
    ).fetchone()

    if not voter:
        return jsonify({'message': 'Voter not found'}), 404

    db.execute('DELETE FROM voters WHERE id = ?', (voter_db_id,))
    db.execute('DELETE FROM voter_embeddings WHERE voter_db_id = ?', (voter_db_id,))
    db.commit()

    if voter['photo_path']:
        photo_path = os.path.join(
            current_app.config['VOTER_PHOTOS_FOLDER'],
            voter['photo_path']
        )
        if os.path.exists(photo_path):
            try:
                os.remove(photo_path)
            except OSError:
                pass

    return jsonify({'message': 'Voter removed successfully'}), 200


@voters_bp.route('/recent', methods=['GET'])
@token_required
def get_recent():
    db = get_db()
    rows = db.execute(
        '''
        SELECT id, name, registered_at, has_voted
        FROM voters ORDER BY registered_at DESC LIMIT 10
        '''
    ).fetchall()

    recent = [{
        'id': row['id'],
        'name': row['name'],
        'time': row['registered_at'],
        'status': 'Authorized' if row['has_voted'] else 'Not Voted'
    } for row in rows]

    return jsonify(recent), 200
